Add TaskLog message for propagating worker stdout/err back to client (#183)
* Add TaskLog message for propagating worker stdout/err back to client

Signed-off-by: eric <eric117649@gmail.com>

* Stream output as it is written rather than waiting for the task to complete

Signed-off-by: eric <eric117649@gmail.com>

* Add flag to enable output streaming

Signed-off-by: eric <eric117649@gmail.com>

* Print task output directly to stdout/err without prefix

Signed-off-by: eric <eric117649@gmail.com>

* Run black

Signed-off-by: eric <eric117649@gmail.com>

* Rename variables

Signed-off-by: eric <eric117649@gmail.com>

* StreamingBuffer Revisions

- Inherit IOBase instead of StringIO so it doesn't keep the test buffer in-memory
- Don't need to print output on worker side
- Don't need lock since SyncConnector is thread safe
- Print every line on client, and without changing line ends
- Remove redundant default value set for stream_output

Signed-off-by: eric <eric117649@gmail.com>

* Refactor streaming redirect and use TextIOBase to fix mypy lint error

Found 2 errors in 1 file (checked 156 source files)
scaler/worker/agent/processor/processor.py:208: error: Value of type variable "_T_io" of "redirect_stderr" cannot be "StreamingBuffer"  [type-var]

Signed-off-by: eric <eric117649@gmail.com>

* Simplify client printing

Signed-off-by: eric <eric117649@gmail.com>

* Refactor task processing to use context manager for StreamingBuffer

Signed-off-by: eric <eric117649@gmail.com>

---------

Signed-off-by: eric <eric117649@gmail.com>
Co-authored-by: sharpener6 <1sc2l4qi@duck.com>